name = "navsphere"
compatibility_date = "2025-08-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23lium6k8x5KPsrqIN"
GITHUB_OWNER = "lxmings"
GITHUB_REPO = "Navigation"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://guide.atoposs.com/api/auth"
NEXT_PUBLIC_API_URL="https://guide.atoposs.com"

